export const PUT_PRODUCT_BEGIN = 'PUT_PRODUCT_BEGIN';
export const PUT_PRODUCT_SUCCESS = 'PUT_PRODUCT_SUCCESS';
export const PUT_PRODUCT_FAILED = 'PUT_PRODUCT_FAILED';
export const PUT_PRODUCT_DISMISS_RESPONSE = 'PUT_PRODUCT_DISMISS_RESPONSE';
export const PUT_PRODUCT_DISMISS_ERROR = 'PUT_PRODUCT_DISMISS_ERROR';
