export const GET_PRODUCT_BEGIN = 'GET_PRODUCT_BEGIN';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';
export const GET_PRODUCT_DISMISS_RESPONSE = 'GET_PRODUCT_DISMISS_RESPONSE';
export const GET_PRODUCT_DISMISS_ERROR = 'GET_PRODUCT_DISMISS_ERROR';
