export const DELETE_PRODUCT_BEGIN = 'DELETE_PRODUCT_BEGIN';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';
export const DELETE_PRODUCT_DISMISS_RESPONSE = 'DELETE_PRODUCT_DISMISS_RESPONSE';
export const DELETE_PRODUCT_DISMISS_ERROR = 'DELETE_PRODUCT_DISMISS_ERROR';
