export const POST_PRODUCT_BEGIN = 'POST_PRODUCT_BEGIN';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_FAILED = 'POST_PRODUCT_FAILED';
export const POST_PRODUCT_DISMISS_RESPONSE = 'POST_PRODUCT_DISMISS_RESPONSE';
export const POST_PRODUCT_DISMISS_ERROR = 'POST_PRODUCT_DISMISS_ERROR';
