export const GET_PRODUCT_LIST_BEGIN = 'GET_PRODUCT_LIST_BEGIN';
export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';
export const GET_PRODUCT_LIST_FAILED = 'GET_PRODUCT_LIST_FAILED';
export const GET_PRODUCT_LIST_DISMISS_RESPONSE = 'GET_PRODUCT_LIST_DISMISS_RESPONSE';
export const GET_PRODUCT_LIST_DISMISS_ERROR = 'GET_PRODUCT_LIST_DISMISS_ERROR';
